#import system

# const waylandc = gorge("pkg-config --cflags wayland-client")
# const xkbcommonc = gorge("pkg-config --cflags xkbcommon")

# {.passC:"-O3 -I./lvgl "lvgl/linux_x64/ & waylandc & "lvgl/linux_x64/ "lvgl/linux_x64/ & xkbcommonc .}
#const installPath {.global.} = gorge("nimble path lvgl")
# const destDir {.strdefine.} = "lvgl/linux_x64/"
# const tmp = "lvgl/linux_x64/-o "lvgl/linux_x64/ & destDir & "lvgl/linux_x64/lv_fs_cbfs.c.c.o"
# echo destDir
# lvgl/linux_x64/
#lvgl/linux_x64/
{.link: "lvgl/linux_x64/lv_font_montserrat_30.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_46.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_28_compressed.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_12_subpx.c.o".}
{.link: "lvgl/linux_x64/lv_font.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_40.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_26.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_34.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_42.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_10.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_14.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_44.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_18.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_8.c.o".}
{.link: "lvgl/linux_x64/lv_font_dejavu_16_persian_hebrew.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_24.c.o".}
{.link: "lvgl/linux_x64/lv_font_unscii_16.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_48.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_22.c.o".}
{.link: "lvgl/linux_x64/lv_font_fmt_txt.c.o".}
{.link: "lvgl/linux_x64/lv_font_simsun_16_cjk.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_38.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_32.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_28.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_12.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_16.c.o".}
{.link: "lvgl/linux_x64/lv_font_loader.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_36.c.o".}
{.link: "lvgl/linux_x64/lv_font_unscii_8.c.o".}
{.link: "lvgl/linux_x64/lv_font_montserrat_20.c.o".}
{.link: "lvgl/linux_x64/lv_hal_tick.c.o".}
{.link: "lvgl/linux_x64/lv_theme_default.c.o".}
{.link: "lvgl/linux_x64/lv_theme_mono.c.o".}
{.link: "lvgl/linux_x64/lv_theme_basic.c.o".}
{.link: "lvgl/linux_x64/lv_grid.c.o".}
{.link: "lvgl/linux_x64/lv_flex.c.o".}
{.link: "lvgl/linux_x64/lv_draw_transform.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_dither.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_layer.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_rect.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_img.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_letter.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_gradient.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_polygon.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_arc.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_transform.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_blend.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sw_line.c.o".}
{.link: "lvgl/linux_x64/lv_draw_layer.c.o".}
{.link: "lvgl/linux_x64/lv_draw_mask.c.o".}
{.link: "lvgl/linux_x64/lv_draw_rect.c.o".}
{.link: "lvgl/linux_x64/lv_draw_triangle.c.o".}
{.link: "lvgl/linux_x64/lv_img_decoder.c.o".}
#{.link: "lvgl/linux_x64/swm341_dma2lv_gpu_swm341_dma2d.c.o".}
{.link: "lvgl/linux_x64/lv_img_cache.c.o".}
#{.link: "lvgl/linux_x64/arm2lv_gpu_arm2d.c.o".}
{.link: "lvgl/linux_x64/lv_draw_img.c.o".}
{.link: "lvgl/linux_x64/lv_vglite_buf.c.o".}
{.link: "lvgl/linux_x64/lv_draw_vglite_blend.c.o".}
{.link: "lvgl/linux_x64/lv_draw_vglite.c.o".}
{.link: "lvgl/linux_x64/lv_draw_vglite_rect.c.o".}
{.link: "lvgl/linux_x64/lv_draw_vglite_arc.c.o".}
{.link: "lvgl/linux_x64/lv_vglite_utils.c.o".}
{.link: "lvgl/linux_x64/lv_draw_vglite_line.c.o".}
{.link: "lvgl/linux_x64/lv_draw_pxp_blend.c.o".}
{.link: "lvgl/linux_x64/lv_draw_pxp.c.o".}
{.link: "lvgl/linux_x64/lv_gpu_nxp_pxp_osa.c.o".}
{.link: "lvgl/linux_x64/lv_gpu_nxp_pxp.c.o".}
{.link: "lvgl/linux_x64/lv_draw_label.c.o".}
{.link: "lvgl/linux_x64/lv_img_buf.c.o".}
{.link: "lvgl/linux_x64/lv_draw_line.c.o".}
{.link: "lvgl/linux_x64/lv_draw_arc.c.o".}
#{.link: "lvgl/linux_x64/gd32lv_gpu_gd32_ipa.c.o".}
#{.link: "lvgl/linux_x64/stm32_dma2lv_gpu_stm32_dma2d.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_utils.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_stack_blur.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_texture_cache.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_label.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_line.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_mask.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_arc.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_img.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_composite.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_polygon.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_rect.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_bg.c.o".}
{.link: "lvgl/linux_x64/lv_draw_sdl_layer.c.o".}
{.link: "lvgl/linux_x64/lv_img_cache_builtin.c.o".}
{.link: "lvgl/linux_x64/lv_draw.c.o".}
{.link: "lvgl/linux_x64/lv_obj_scroll.c.o".}
{.link: "lvgl/linux_x64/lv_obj_event.c.o".}
{.link: "lvgl/linux_x64/lv_obj_style_gen.c.o".}
{.link: "lvgl/linux_x64/lv_disp.c.o".}
{.link: "lvgl/linux_x64/lv_obj_tree.c.o".}
{.link: "lvgl/linux_x64/lv_obj_style.c.o".}
{.link: "lvgl/linux_x64/lv_theme.c.o".}
{.link: "lvgl/linux_x64/lv_group.c.o".}
{.link: "lvgl/linux_x64/lv_obj.c.o".}
{.link: "lvgl/linux_x64/lv_indev.c.o".}
{.link: "lvgl/linux_x64/lv_obj_draw.c.o".}
{.link: "lvgl/linux_x64/lv_obj_class.c.o".}
{.link: "lvgl/linux_x64/lv_obj_pos.c.o".}
{.link: "lvgl/linux_x64/lv_refr.c.o".}
{.link: "lvgl/linux_x64/lv_indev_scroll.c.o".}
{.link: "lvgl/linux_x64/lv_tileview.c.o".}
{.link: "lvgl/linux_x64/lv_spinner.c.o".}
{.link: "lvgl/linux_x64/lv_table.c.o".}
{.link: "lvgl/linux_x64/lv_textarea.c.o".}
{.link: "lvgl/linux_x64/lv_slider.c.o".}
{.link: "lvgl/linux_x64/lv_chart.c.o".}
{.link: "lvgl/linux_x64/lv_btn.c.o".}
{.link: "lvgl/linux_x64/lv_img.c.o".}
{.link: "lvgl/linux_x64/lv_switch.c.o".}
{.link: "lvgl/linux_x64/lv_span.c.o".}
{.link: "lvgl/linux_x64/lv_dropdown.c.o".}
{.link: "lvgl/linux_x64/lv_roller.c.o".}
{.link: "lvgl/linux_x64/lv_btnmatrix.c.o".}
{.link: "lvgl/linux_x64/lv_label.c.o".}
{.link: "lvgl/linux_x64/lv_tabview.c.o".}
{.link: "lvgl/linux_x64/lv_spinbox.c.o".}
{.link: "lvgl/linux_x64/lv_colorwheel.c.o".}
{.link: "lvgl/linux_x64/lv_win.c.o".}
{.link: "lvgl/linux_x64/lv_arc.c.o".}
{.link: "lvgl/linux_x64/lv_meter.c.o".}
{.link: "lvgl/linux_x64/lv_calendar_header_arrow.c.o".}
{.link: "lvgl/linux_x64/lv_calendar_header_dropdown.c.o".}
{.link: "lvgl/linux_x64/lv_calendar.c.o".}
{.link: "lvgl/linux_x64/lv_menu.c.o".}
{.link: "lvgl/linux_x64/lv_keyboard.c.o".}
{.link: "lvgl/linux_x64/lv_checkbox.c.o".}
{.link: "lvgl/linux_x64/lv_msgbox.c.o".}
{.link: "lvgl/linux_x64/lv_objx_templ.c.o".}
{.link: "lvgl/linux_x64/lv_canvas.c.o".}
{.link: "lvgl/linux_x64/lv_list.c.o".}
{.link: "lvgl/linux_x64/lv_bar.c.o".}
{.link: "lvgl/linux_x64/lv_led.c.o".}
{.link: "lvgl/linux_x64/lv_animimg.c.o".}
{.link: "lvgl/linux_x64/lv_line.c.o".}
{.link: "lvgl/linux_x64/lv_imgbtn.c.o".}
{.link: "lvgl/linux_x64/lv_linux_drm.c.o".}
{.link: "lvgl/linux_x64/lv_linux_fbdev.c.o".}
{.link: "lvgl/linux_x64/lv_sdl_mousewheel.c.o".}
{.link: "lvgl/linux_x64/lv_sdl_mouse.c.o".}
{.link: "lvgl/linux_x64/lv_sdl_keyboard.c.o".}
{.link: "lvgl/linux_x64/lv_sdl_window.c.o".}
{.link: "lvgl/linux_x64/lv_sysmon.c.o".}
{.link: "lvgl/linux_x64/lv_fragment_manager.c.o".}
{.link: "lvgl/linux_x64/lv_fragment.c.o".}
{.link: "lvgl/linux_x64/lv_ime_pinyin.c.o".}
{.link: "lvgl/linux_x64/lv_monkey.c.o".}
{.link: "lvgl/linux_x64/lv_gridnav.c.o".}
{.link: "lvgl/linux_x64/lv_imgfont.c.o".}
{.link: "lvgl/linux_x64/lv_file_explorer.c.o".}
{.link: "lvgl/linux_x64/lv_msg.c.o".}
{.link: "lvgl/linux_x64/lv_snapshot.c.o".}
{.link: "lvgl/linux_x64/lv_utils.c.o".}
{.link: "lvgl/linux_x64/lv_async.c.o".}
{.link: "lvgl/linux_x64/lv_bidi.c.o".}
{.link: "lvgl/linux_x64/lv_ll.c.o".}
{.link: "lvgl/linux_x64/lv_templ.c.o".}
{.link: "lvgl/linux_x64/lv_fs.c.o".}
{.link: "lvgl/linux_x64/lv_math.c.o".}
{.link: "lvgl/linux_x64/lv_event.c.o".}
{.link: "lvgl/linux_x64/lv_style.c.o".}
{.link: "lvgl/linux_x64/lv_color.c.o".}
{.link: "lvgl/linux_x64/lv_timer.c.o".}
{.link: "lvgl/linux_x64/lv_gc.c.o".}
{.link: "lvgl/linux_x64/lv_log.c.o".}
{.link: "lvgl/linux_x64/lv_txt_ap.c.o".}
{.link: "lvgl/linux_x64/lv_area.c.o".}
{.link: "lvgl/linux_x64/lv_tlsf.c.o".}
{.link: "lvgl/linux_x64/lv_printf.c.o".}
{.link: "lvgl/linux_x64/lv_txt.c.o".}
{.link: "lvgl/linux_x64/lv_style_gen.c.o".}
{.link: "lvgl/linux_x64/lv_anim.c.o".}
{.link: "lvgl/linux_x64/lv_profiler_builtin.c.o".}
{.link: "lvgl/linux_x64/lv_memcpy_builtin.c.o".}
{.link: "lvgl/linux_x64/lv_malloc_builtin.c.o".}
{.link: "lvgl/linux_x64/lv_mem.c.o".}
{.link: "lvgl/linux_x64/lv_anim_timeline.c.o".}
{.link: "lvgl/linux_x64/lv_lru.c.o".}
{.link: "lvgl/linux_x64/tjpgd.c.o".}
{.link: "lvgl/linux_x64/lv_sjpg.c.o".}
{.link: "lvgl/linux_x64/lv_rlottie.c.o".}
{.link: "lvgl/linux_x64/lv_ffmpeg.c.o".}
{.link: "lvgl/linux_x64/lv_fs_win32.c.o".}
{.link: "lvgl/linux_x64/lv_fs_posix.c.o".}
{.link: "lvgl/linux_x64/lv_fs_cbfs.c.o".}
{.link: "lvgl/linux_x64/lv_fs_fatfs.c.o".}
{.link: "lvgl/linux_x64/lv_fs_stdio.c.o".}
{.link: "lvgl/linux_x64/code128.c.o".}
{.link: "lvgl/linux_x64/lv_barcode.c.o".}
{.link: "lvgl/linux_x64/lv_tiny_ttf.c.o".}
{.link: "lvgl/linux_x64/lv_ftsystem.c.o".}
{.link: "lvgl/linux_x64/lv_freetype.c.o".}
{.link: "lvgl/linux_x64/gifdec.c.o".}
{.link: "lvgl/linux_x64/lv_gif.c.o".}
{.link: "lvgl/linux_x64/lodepng.c.o".}
{.link: "lvgl/linux_x64/lv_png.c.o".}
{.link: "lvgl/linux_x64/qrcodegen.c.o".}
{.link: "lvgl/linux_x64/lv_qrcode.c.o".}
{.link: "lvgl/linux_x64/lv_bmp.c.o".}
