{.compile: "../components/lvgl/src/font/lv_font_montserrat_30.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_46.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_28_compressed.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_12_subpx.c".}
{.compile: "../components/lvgl/src/font/lv_font.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_40.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_26.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_34.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_42.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_10.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_14.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_44.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_18.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_8.c".}
{.compile: "../components/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_24.c".}
{.compile: "../components/lvgl/src/font/lv_font_unscii_16.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_48.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_22.c".}
{.compile: "../components/lvgl/src/font/lv_font_fmt_txt.c".}
{.compile: "../components/lvgl/src/font/lv_font_simsun_16_cjk.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_38.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_32.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_28.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_12.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_16.c".}
{.compile: "../components/lvgl/src/font/lv_font_loader.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_36.c".}
{.compile: "../components/lvgl/src/font/lv_font_unscii_8.c".}
{.compile: "../components/lvgl/src/font/lv_font_montserrat_20.c".}
{.compile: "../components/lvgl/src/hal/lv_hal_tick.c".}
{.compile: "../components/lvgl/src/themes/default/lv_theme_default.c".}
{.compile: "../components/lvgl/src/themes/mono/lv_theme_mono.c".}
{.compile: "../components/lvgl/src/themes/basic/lv_theme_basic.c".}
{.compile: "../components/lvgl/src/layouts/grid/lv_grid.c".}
{.compile: "../components/lvgl/src/layouts/flex/lv_flex.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_transform.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_dither.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_layer.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_rect.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_img.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_letter.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_gradient.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_polygon.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_arc.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_transform.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_blend.c".}
{.compile: "../components/lvgl/src/draw/sw/lv_draw_sw_line.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_layer.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_mask.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_rect.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_triangle.c".}
{.compile: "../components/lvgl/src/draw/lv_img_decoder.c".}
{.compile: "../components/lvgl/src/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c".}
{.compile: "../components/lvgl/src/draw/lv_img_cache.c".}
{.compile: "../components/lvgl/src/draw/arm2d/lv_gpu_arm2d.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_img.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_draw_vglite_blend.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_draw_vglite_rect.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c".}
{.compile: "../components/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c".}
{.compile: "../components/lvgl/src/draw/nxp/pxp/lv_draw_pxp_blend.c".}
{.compile: "../components/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c".}
{.compile: "../components/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c".}
{.compile: "../components/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_label.c".}
{.compile: "../components/lvgl/src/draw/lv_img_buf.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_line.c".}
{.compile: "../components/lvgl/src/draw/lv_draw_arc.c".}
{.compile: "../components/lvgl/src/draw/gd32_ipa/lv_gpu_gd32_ipa.c".}
{.compile: "../components/lvgl/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_utils.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_stack_blur.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_label.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_line.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_mask.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_arc.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_img.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_composite.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_polygon.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_rect.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_bg.c".}
{.compile: "../components/lvgl/src/draw/sdl/lv_draw_sdl_layer.c".}
{.compile: "../components/lvgl/src/draw/lv_img_cache_builtin.c".}
{.compile: "../components/lvgl/src/draw/lv_draw.c".}
{.compile: "../components/lvgl/src/core/lv_obj_scroll.c".}
{.compile: "../components/lvgl/src/core/lv_obj_event.c".}
{.compile: "../components/lvgl/src/core/lv_obj_style_gen.c".}
{.compile: "../components/lvgl/src/core/lv_disp.c".}
{.compile: "../components/lvgl/src/core/lv_obj_tree.c".}
{.compile: "../components/lvgl/src/core/lv_obj_style.c".}
{.compile: "../components/lvgl/src/core/lv_theme.c".}
{.compile: "../components/lvgl/src/core/lv_group.c".}
{.compile: "../components/lvgl/src/core/lv_obj.c".}
{.compile: "../components/lvgl/src/core/lv_indev.c".}
{.compile: "../components/lvgl/src/core/lv_obj_draw.c".}
{.compile: "../components/lvgl/src/core/lv_obj_class.c".}
{.compile: "../components/lvgl/src/core/lv_obj_pos.c".}
{.compile: "../components/lvgl/src/core/lv_refr.c".}
{.compile: "../components/lvgl/src/core/lv_indev_scroll.c".}
{.compile: "../components/lvgl/src/widgets/tileview/lv_tileview.c".}
{.compile: "../components/lvgl/src/widgets/spinner/lv_spinner.c".}
{.compile: "../components/lvgl/src/widgets/table/lv_table.c".}
{.compile: "../components/lvgl/src/widgets/textarea/lv_textarea.c".}
{.compile: "../components/lvgl/src/widgets/slider/lv_slider.c".}
{.compile: "../components/lvgl/src/widgets/chart/lv_chart.c".}
{.compile: "../components/lvgl/src/widgets/btn/lv_btn.c".}
{.compile: "../components/lvgl/src/widgets/img/lv_img.c".}
{.compile: "../components/lvgl/src/widgets/switch/lv_switch.c".}
{.compile: "../components/lvgl/src/widgets/span/lv_span.c".}
{.compile: "../components/lvgl/src/widgets/dropdown/lv_dropdown.c".}
{.compile: "../components/lvgl/src/widgets/roller/lv_roller.c".}
{.compile: "../components/lvgl/src/widgets/btnmatrix/lv_btnmatrix.c".}
{.compile: "../components/lvgl/src/widgets/label/lv_label.c".}
{.compile: "../components/lvgl/src/widgets/tabview/lv_tabview.c".}
{.compile: "../components/lvgl/src/widgets/spinbox/lv_spinbox.c".}
{.compile: "../components/lvgl/src/widgets/colorwheel/lv_colorwheel.c".}
{.compile: "../components/lvgl/src/widgets/win/lv_win.c".}
{.compile: "../components/lvgl/src/widgets/arc/lv_arc.c".}
{.compile: "../components/lvgl/src/widgets/meter/lv_meter.c".}
{.compile: "../components/lvgl/src/widgets/calendar/lv_calendar_header_arrow.c".}
{.compile: "../components/lvgl/src/widgets/calendar/lv_calendar_header_dropdown.c".}
{.compile: "../components/lvgl/src/widgets/calendar/lv_calendar.c".}
{.compile: "../components/lvgl/src/widgets/menu/lv_menu.c".}
{.compile: "../components/lvgl/src/widgets/keyboard/lv_keyboard.c".}
{.compile: "../components/lvgl/src/widgets/checkbox/lv_checkbox.c".}
{.compile: "../components/lvgl/src/widgets/msgbox/lv_msgbox.c".}
{.compile: "../components/lvgl/src/widgets/objx_templ/lv_objx_templ.c".}
{.compile: "../components/lvgl/src/widgets/canvas/lv_canvas.c".}
{.compile: "../components/lvgl/src/widgets/list/lv_list.c".}
{.compile: "../components/lvgl/src/widgets/bar/lv_bar.c".}
{.compile: "../components/lvgl/src/widgets/led/lv_led.c".}
{.compile: "../components/lvgl/src/widgets/animimg/lv_animimg.c".}
{.compile: "../components/lvgl/src/widgets/line/lv_line.c".}
{.compile: "../components/lvgl/src/widgets/imgbtn/lv_imgbtn.c".}
{.compile: "../components/lvgl/src/dev/disp/drm/lv_linux_drm.c".}
{.compile: "../components/lvgl/src/dev/disp/fb/lv_linux_fbdev.c".}
{.compile: "../components/lvgl/src/dev/sdl/lv_sdl_mousewheel.c".}
{.compile: "../components/lvgl/src/dev/sdl/lv_sdl_mouse.c".}
{.compile: "../components/lvgl/src/dev/sdl/lv_sdl_keyboard.c".}
{.compile: "../components/lvgl/src/dev/sdl/lv_sdl_window.c".}
{.compile: "../components/lvgl/src/others/sysmon/lv_sysmon.c".}
{.compile: "../components/lvgl/src/others/fragment/lv_fragment_manager.c".}
{.compile: "../components/lvgl/src/others/fragment/lv_fragment.c".}
{.compile: "../components/lvgl/src/others/ime/lv_ime_pinyin.c".}
{.compile: "../components/lvgl/src/others/monkey/lv_monkey.c".}
{.compile: "../components/lvgl/src/others/gridnav/lv_gridnav.c".}
{.compile: "../components/lvgl/src/others/imgfont/lv_imgfont.c".}
{.compile: "../components/lvgl/src/others/file_explorer/lv_file_explorer.c".}
{.compile: "../components/lvgl/src/others/msg/lv_msg.c".}
{.compile: "../components/lvgl/src/others/snapshot/lv_snapshot.c".}
{.compile: "../components/lvgl/src/misc/lv_utils.c".}
{.compile: "../components/lvgl/src/misc/lv_async.c".}
{.compile: "../components/lvgl/src/misc/lv_bidi.c".}
{.compile: "../components/lvgl/src/misc/lv_ll.c".}
{.compile: "../components/lvgl/src/misc/lv_templ.c".}
{.compile: "../components/lvgl/src/misc/lv_fs.c".}
{.compile: "../components/lvgl/src/misc/lv_math.c".}
{.compile: "../components/lvgl/src/misc/lv_event.c".}
{.compile: "../components/lvgl/src/misc/lv_style.c".}
{.compile: "../components/lvgl/src/misc/lv_color.c".}
{.compile: "../components/lvgl/src/misc/lv_timer.c".}
{.compile: "../components/lvgl/src/misc/lv_gc.c".}
{.compile: "../components/lvgl/src/misc/lv_log.c".}
{.compile: "../components/lvgl/src/misc/lv_txt_ap.c".}
{.compile: "../components/lvgl/src/misc/lv_area.c".}
{.compile: "../components/lvgl/src/misc/lv_tlsf.c".}
{.compile: "../components/lvgl/src/misc/lv_printf.c".}
{.compile: "../components/lvgl/src/misc/lv_txt.c".}
{.compile: "../components/lvgl/src/misc/lv_style_gen.c".}
{.compile: "../components/lvgl/src/misc/lv_anim.c".}
{.compile: "../components/lvgl/src/misc/lv_profiler_builtin.c".}
{.compile: "../components/lvgl/src/misc/lv_memcpy_builtin.c".}
{.compile: "../components/lvgl/src/misc/lv_malloc_builtin.c".}
{.compile: "../components/lvgl/src/misc/lv_mem.c".}
{.compile: "../components/lvgl/src/misc/lv_anim_timeline.c".}
{.compile: "../components/lvgl/src/misc/lv_lru.c".}
{.compile: "../components/lvgl/src/libs/sjpg/tjpgd.c".}
{.compile: "../components/lvgl/src/libs/sjpg/lv_sjpg.c".}
{.compile: "../components/lvgl/src/libs/rlottie/lv_rlottie.c".}
{.compile: "../components/lvgl/src/libs/ffmpeg/lv_ffmpeg.c".}
{.compile: "../components/lvgl/src/libs/fsdrv/lv_fs_win32.c".}
{.compile: "../components/lvgl/src/libs/fsdrv/lv_fs_posix.c".}
{.compile: "../components/lvgl/src/libs/fsdrv/lv_fs_cbfs.c".}
{.compile: "../components/lvgl/src/libs/fsdrv/lv_fs_fatfs.c".}
{.compile: "../components/lvgl/src/libs/fsdrv/lv_fs_stdio.c".}
{.compile: "../components/lvgl/src/libs/barcode/code128.c".}
{.compile: "../components/lvgl/src/libs/barcode/lv_barcode.c".}
{.compile: "../components/lvgl/src/libs/tiny_ttf/lv_tiny_ttf.c".}
{.compile: "../components/lvgl/src/libs/freetype/lv_ftsystem.c".}
{.compile: "../components/lvgl/src/libs/freetype/lv_freetype.c".}
{.compile: "../components/lvgl/src/libs/gif/gifdec.c".}
{.compile: "../components/lvgl/src/libs/gif/lv_gif.c".}
{.compile: "../components/lvgl/src/libs/png/lodepng.c".}
{.compile: "../components/lvgl/src/libs/png/lv_png.c".}
{.compile: "../components/lvgl/src/libs/qrcode/qrcodegen.c".}
{.compile: "../components/lvgl/src/libs/qrcode/lv_qrcode.c".}
{.compile: "../components/lvgl/src/libs/bmp/lv_bmp.c".}
