{.compile: "../submodules/lvgl/src/lv_init.c".}
{.compile: "../submodules/lvgl/src/libs/qrcode/lv_qrcode.c".}
{.compile: "../submodules/lvgl/src/libs/qrcode/qrcodegen.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_posix.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_win32.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_arduino_sd.cpp".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_cbfs.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_littlefs.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_fatfs.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_memfs.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_stdio.c".}
{.compile: "../submodules/lvgl/src/libs/fsdrv/lv_fs_arduino_esp_littlefs.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgRender.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieModel.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwRaster.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgTaskScheduler.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLines.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgAccessor.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSvgPath.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgText.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieAnimation.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgPaint.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgShape.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgXmlParser.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgMath.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwCanvas.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwRle.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgRawLoader.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieInterpolator.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieLoader.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgGlCanvas.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgCapi.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSvgCssStyle.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgInitializer.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwShape.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieBuilder.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgPicture.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgStr.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgScene.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSvgSceneBuilder.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieParser.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgCanvas.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgFill.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwImage.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwMath.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSvgUtil.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwStroke.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLoader.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieExpressions.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgLottieParserHandler.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwMemPool.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgAnimation.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgWgCanvas.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSaver.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwRenderer.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSwFill.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgSvgLoader.cpp".}
{.compile: "../submodules/lvgl/src/libs/thorvg/tvgCompressor.cpp".}
{.compile: "../submodules/lvgl/src/libs/tiny_ttf/lv_tiny_ttf.c".}
{.compile: "../submodules/lvgl/src/libs/lodepng/lodepng.c".}
{.compile: "../submodules/lvgl/src/libs/lodepng/lv_lodepng.c".}
{.compile: "../submodules/lvgl/src/libs/lz4/lz4.c".}
{.compile: "../submodules/lvgl/src/libs/libpng/lv_libpng.c".}
{.compile: "../submodules/lvgl/src/libs/bmp/lv_bmp.c".}
{.compile: "../submodules/lvgl/src/libs/barcode/lv_barcode.c".}
{.compile: "../submodules/lvgl/src/libs/barcode/code128.c".}
{.compile: "../submodules/lvgl/src/libs/bin_decoder/lv_bin_decoder.c".}
{.compile: "../submodules/lvgl/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c".}
{.compile: "../submodules/lvgl/src/libs/ffmpeg/lv_ffmpeg.c".}
{.compile: "../submodules/lvgl/src/libs/freetype/lv_freetype_glyph.c".}
{.compile: "../submodules/lvgl/src/libs/freetype/lv_ftsystem.c".}
{.compile: "../submodules/lvgl/src/libs/freetype/lv_freetype.c".}
{.compile: "../submodules/lvgl/src/libs/freetype/lv_freetype_image.c".}
{.compile: "../submodules/lvgl/src/libs/freetype/lv_freetype_outline.c".}
{.compile: "../submodules/lvgl/src/libs/rle/lv_rle.c".}
{.compile: "../submodules/lvgl/src/libs/gif/gifdec.c".}
{.compile: "../submodules/lvgl/src/libs/gif/lv_gif.c".}
{.compile: "../submodules/lvgl/src/libs/rlottie/lv_rlottie.c".}
{.compile: "../submodules/lvgl/src/libs/tjpgd/lv_tjpgd.c".}
{.compile: "../submodules/lvgl/src/libs/tjpgd/tjpgd.c".}
{.compile: "../submodules/lvgl/src/themes/lv_theme.c".}
{.compile: "../submodules/lvgl/src/themes/mono/lv_theme_mono.c".}
{.compile: "../submodules/lvgl/src/themes/default/lv_theme_default.c".}
{.compile: "../submodules/lvgl/src/themes/simple/lv_theme_simple.c".}
{.compile: "../submodules/lvgl/src/display/lv_display.c".}
{.compile: "../submodules/lvgl/src/drivers/glfw/lv_opengles_texture.c".}
{.compile: "../submodules/lvgl/src/drivers/glfw/lv_glfw_window.c".}
{.compile: "../submodules/lvgl/src/drivers/glfw/lv_opengles_debug.c".}
{.compile: "../submodules/lvgl/src/drivers/glfw/lv_opengles_driver.c".}
{.compile: "../submodules/lvgl/src/drivers/display/st7796/lv_st7796.c".}
{.compile: "../submodules/lvgl/src/drivers/display/fb/lv_linux_fbdev.c".}
{.compile: "../submodules/lvgl/src/drivers/display/st7789/lv_st7789.c".}
{.compile: "../submodules/lvgl/src/drivers/display/tft_espi/lv_tft_espi.cpp".}
{.compile: "../submodules/lvgl/src/drivers/display/ili9341/lv_ili9341.c".}
{.compile: "../submodules/lvgl/src/drivers/display/renesas_glcdc/lv_renesas_glcdc.c".}
{.compile: "../submodules/lvgl/src/drivers/display/drm/lv_linux_drm.c".}
{.compile: "../submodules/lvgl/src/drivers/display/lcd/lv_lcd_generic_mipi.c".}
{.compile: "../submodules/lvgl/src/drivers/display/st7735/lv_st7735.c".}
{.compile: "../submodules/lvgl/src/drivers/wayland/lv_wayland.c".}
{.compile: "../submodules/lvgl/src/drivers/wayland/lv_wayland_smm.c".}
{.compile: "../submodules/lvgl/src/drivers/sdl/lv_sdl_keyboard.c".}
{.compile: "../submodules/lvgl/src/drivers/sdl/lv_sdl_mousewheel.c".}
{.compile: "../submodules/lvgl/src/drivers/sdl/lv_sdl_window.c".}
{.compile: "../submodules/lvgl/src/drivers/sdl/lv_sdl_mouse.c".}
{.compile: "../submodules/lvgl/src/drivers/qnx/lv_qnx.c".}
{.compile: "../submodules/lvgl/src/drivers/windows/lv_windows_context.c".}
{.compile: "../submodules/lvgl/src/drivers/windows/lv_windows_input.c".}
{.compile: "../submodules/lvgl/src/drivers/windows/lv_windows_display.c".}
{.compile: "../submodules/lvgl/src/drivers/x11/lv_x11_display.c".}
{.compile: "../submodules/lvgl/src/drivers/x11/lv_x11_input.c".}
{.compile: "../submodules/lvgl/src/drivers/evdev/lv_evdev.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_fbdev.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_cache.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_entry.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_touchscreen.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_profiler.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_image_cache.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_libuv.c".}
{.compile: "../submodules/lvgl/src/drivers/nuttx/lv_nuttx_lcd.c".}
{.compile: "../submodules/lvgl/src/drivers/libinput/lv_libinput.c".}
{.compile: "../submodules/lvgl/src/drivers/libinput/lv_xkb.c".}
{.compile: "../submodules/lvgl/src/misc/lv_lru.c".}
{.compile: "../submodules/lvgl/src/misc/lv_area.c".}
{.compile: "../submodules/lvgl/src/misc/lv_style.c".}
{.compile: "../submodules/lvgl/src/misc/lv_utils.c".}
{.compile: "../submodules/lvgl/src/misc/lv_profiler_builtin.c".}
{.compile: "../submodules/lvgl/src/misc/lv_anim.c".}
{.compile: "../submodules/lvgl/src/misc/lv_log.c".}
{.compile: "../submodules/lvgl/src/misc/lv_color_op.c".}
{.compile: "../submodules/lvgl/src/misc/lv_array.c".}
{.compile: "../submodules/lvgl/src/misc/lv_bidi.c".}
{.compile: "../submodules/lvgl/src/misc/lv_matrix.c".}
{.compile: "../submodules/lvgl/src/misc/lv_fs.c".}
{.compile: "../submodules/lvgl/src/misc/lv_math.c".}
{.compile: "../submodules/lvgl/src/misc/lv_event.c".}
{.compile: "../submodules/lvgl/src/misc/lv_timer.c".}
{.compile: "../submodules/lvgl/src/misc/lv_ll.c".}
{.compile: "../submodules/lvgl/src/misc/lv_rb.c".}
{.compile: "../submodules/lvgl/src/misc/lv_text_ap.c".}
{.compile: "../submodules/lvgl/src/misc/lv_text.c".}
{.compile: "../submodules/lvgl/src/misc/lv_palette.c".}
{.compile: "../submodules/lvgl/src/misc/lv_anim_timeline.c".}
{.compile: "../submodules/lvgl/src/misc/lv_templ.c".}
{.compile: "../submodules/lvgl/src/misc/lv_style_gen.c".}
{.compile: "../submodules/lvgl/src/misc/lv_color.c".}
{.compile: "../submodules/lvgl/src/misc/lv_async.c".}
{.compile: "../submodules/lvgl/src/misc/cache/lv_image_header_cache.c".}
{.compile: "../submodules/lvgl/src/misc/cache/lv_image_cache.c".}
{.compile: "../submodules/lvgl/src/misc/cache/lv_cache_lru_rb.c".}
{.compile: "../submodules/lvgl/src/misc/cache/lv_cache_entry.c".}
{.compile: "../submodules/lvgl/src/misc/cache/lv_cache.c".}
{.compile: "../submodules/lvgl/src/tick/lv_tick.c".}
{.compile: "../submodules/lvgl/src/indev/lv_indev.c".}
{.compile: "../submodules/lvgl/src/indev/lv_indev_scroll.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_18.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_simsun_14_cjk.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_fmt_txt.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_8.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_30.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_42.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_36.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_22.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_26.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_16.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_unscii_8.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_24.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_28.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_28_compressed.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_44.c".}
{.compile: "../submodules/lvgl/src/font/lv_binfont_loader.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_simsun_16_cjk.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_48.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_14.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_40.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_38.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_12.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_34.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_20.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_unscii_16.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_10.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_32.c".}
{.compile: "../submodules/lvgl/src/font/lv_font.c".}
{.compile: "../submodules/lvgl/src/font/lv_font_montserrat_46.c".}
{.compile: "../submodules/lvgl/src/others/vg_lite_tvg/vg_lite_tvg.cpp".}
{.compile: "../submodules/lvgl/src/others/vg_lite_tvg/vg_lite_matrix.c".}
{.compile: "../submodules/lvgl/src/others/observer/lv_observer.c".}
{.compile: "../submodules/lvgl/src/others/sysmon/lv_sysmon.c".}
{.compile: "../submodules/lvgl/src/others/snapshot/lv_snapshot.c".}
{.compile: "../submodules/lvgl/src/others/monkey/lv_monkey.c".}
{.compile: "../submodules/lvgl/src/others/ime/lv_ime_pinyin.c".}
{.compile: "../submodules/lvgl/src/others/fragment/lv_fragment.c".}
{.compile: "../submodules/lvgl/src/others/fragment/lv_fragment_manager.c".}
{.compile: "../submodules/lvgl/src/others/imgfont/lv_imgfont.c".}
{.compile: "../submodules/lvgl/src/others/gridnav/lv_gridnav.c".}
{.compile: "../submodules/lvgl/src/others/file_explorer/lv_file_explorer.c".}
{.compile: "../submodules/lvgl/src/osal/lv_os.c".}
{.compile: "../submodules/lvgl/src/osal/lv_os_none.c".}
{.compile: "../submodules/lvgl/src/osal/lv_rtthread.c".}
{.compile: "../submodules/lvgl/src/osal/lv_cmsis_rtos2.c".}
{.compile: "../submodules/lvgl/src/osal/lv_freertos.c".}
{.compile: "../submodules/lvgl/src/osal/lv_mqx.c".}
{.compile: "../submodules/lvgl/src/osal/lv_pthread.c".}
{.compile: "../submodules/lvgl/src/osal/lv_windows.c".}
{.compile: "../submodules/lvgl/src/layouts/lv_layout.c".}
{.compile: "../submodules/lvgl/src/layouts/flex/lv_flex.c".}
{.compile: "../submodules/lvgl/src/layouts/grid/lv_grid.c".}
{.compile: "../submodules/lvgl/src/widgets/dropdown/lv_dropdown.c".}
{.compile: "../submodules/lvgl/src/widgets/led/lv_led.c".}
{.compile: "../submodules/lvgl/src/widgets/objx_templ/lv_objx_templ.c".}
{.compile: "../submodules/lvgl/src/widgets/roller/lv_roller.c".}
{.compile: "../submodules/lvgl/src/widgets/animimage/lv_animimage.c".}
{.compile: "../submodules/lvgl/src/widgets/span/lv_span.c".}
{.compile: "../submodules/lvgl/src/widgets/win/lv_win.c".}
{.compile: "../submodules/lvgl/src/widgets/lottie/lv_lottie.c".}
{.compile: "../submodules/lvgl/src/widgets/slider/lv_slider.c".}
{.compile: "../submodules/lvgl/src/widgets/spinner/lv_spinner.c".}
{.compile: "../submodules/lvgl/src/widgets/arc/lv_arc.c".}
{.compile: "../submodules/lvgl/src/widgets/button/lv_button.c".}
{.compile: "../submodules/lvgl/src/widgets/imagebutton/lv_imagebutton.c".}
{.compile: "../submodules/lvgl/src/widgets/canvas/lv_canvas.c".}
{.compile: "../submodules/lvgl/src/widgets/msgbox/lv_msgbox.c".}
{.compile: "../submodules/lvgl/src/widgets/label/lv_label.c".}
{.compile: "../submodules/lvgl/src/widgets/tabview/lv_tabview.c".}
{.compile: "../submodules/lvgl/src/widgets/line/lv_line.c".}
{.compile: "../submodules/lvgl/src/widgets/scale/lv_scale.c".}
{.compile: "../submodules/lvgl/src/widgets/checkbox/lv_checkbox.c".}
{.compile: "../submodules/lvgl/src/widgets/image/lv_image.c".}
{.compile: "../submodules/lvgl/src/widgets/switch/lv_switch.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_textarea_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_image_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_obj_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_roller_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_keyboard_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_label_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_style_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/property/lv_dropdown_properties.c".}
{.compile: "../submodules/lvgl/src/widgets/list/lv_list.c".}
{.compile: "../submodules/lvgl/src/widgets/table/lv_table.c".}
{.compile: "../submodules/lvgl/src/widgets/bar/lv_bar.c".}
{.compile: "../submodules/lvgl/src/widgets/textarea/lv_textarea.c".}
{.compile: "../submodules/lvgl/src/widgets/tileview/lv_tileview.c".}
{.compile: "../submodules/lvgl/src/widgets/spinbox/lv_spinbox.c".}
{.compile: "../submodules/lvgl/src/widgets/calendar/lv_calendar_header_arrow.c".}
{.compile: "../submodules/lvgl/src/widgets/calendar/lv_calendar_header_dropdown.c".}
{.compile: "../submodules/lvgl/src/widgets/calendar/lv_calendar_chinese.c".}
{.compile: "../submodules/lvgl/src/widgets/calendar/lv_calendar.c".}
{.compile: "../submodules/lvgl/src/widgets/keyboard/lv_keyboard.c".}
{.compile: "../submodules/lvgl/src/widgets/buttonmatrix/lv_buttonmatrix.c".}
{.compile: "../submodules/lvgl/src/widgets/menu/lv_menu.c".}
{.compile: "../submodules/lvgl/src/widgets/chart/lv_chart.c".}
{.compile: "../submodules/lvgl/src/stdlib/lv_mem.c".}
{.compile: "../submodules/lvgl/src/stdlib/clib/lv_sprintf_clib.c".}
{.compile: "../submodules/lvgl/src/stdlib/clib/lv_string_clib.c".}
{.compile: "../submodules/lvgl/src/stdlib/clib/lv_mem_core_clib.c".}
{.compile: "../submodules/lvgl/src/stdlib/micropython/lv_mem_core_micropython.c".}
{.compile: "../submodules/lvgl/src/stdlib/rtthread/lv_string_rtthread.c".}
{.compile: "../submodules/lvgl/src/stdlib/rtthread/lv_sprintf_rtthread.c".}
{.compile: "../submodules/lvgl/src/stdlib/rtthread/lv_mem_core_rtthread.c".}
{.compile: "../submodules/lvgl/src/stdlib/builtin/lv_mem_core_builtin.c".}
{.compile: "../submodules/lvgl/src/stdlib/builtin/lv_tlsf.c".}
{.compile: "../submodules/lvgl/src/stdlib/builtin/lv_string_builtin.c".}
{.compile: "../submodules/lvgl/src/stdlib/builtin/lv_sprintf_builtin.c".}
{.compile: "../submodules/lvgl/src/core/lv_group.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_style_gen.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_id_builtin.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_event.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_property.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_draw.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_pos.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_style.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_scroll.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_tree.c".}
{.compile: "../submodules/lvgl/src/core/lv_refr.c".}
{.compile: "../submodules/lvgl/src/core/lv_obj_class.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_triangle.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_line.c".}
{.compile: "../submodules/lvgl/src/draw/lv_image_decoder.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_buf.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_image.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_rect.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_label.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_arc.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_mask.c".}
{.compile: "../submodules/lvgl/src/draw/lv_draw_vector.c".}
{.compile: "../submodules/lvgl/src/draw/sdl/lv_draw_sdl.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_gradient.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_box_shadow.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_letter.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_img.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_fill.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_mask_rect.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_line.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_triangle.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_arc.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_transform.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_vector.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_border.c".}
{.compile: "../submodules/lvgl/src/draw/sw/lv_draw_sw_mask.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_i1.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_l8.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_al88.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c".}
{.compile: "../submodules/lvgl/src/draw/sw/blend/lv_draw_sw_blend.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_triangle.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_vglite_matrix.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_border.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_buf_vglite.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_fill.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_vglite_path.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_layer.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_img.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_label.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_pxp_cfg.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_pxp_utils.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_draw_buf_pxp.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_draw_pxp_img.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_draw_pxp_layer.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_draw_pxp_fill.c".}
{.compile: "../submodules/lvgl/src/draw/nxp/pxp/lv_pxp_osa.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_label.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_image.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_border.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_line.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c".}
{.compile: "../submodules/lvgl/src/draw/renesas/dave2d/lv_draw_dave2d.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_triangle.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_fill.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_layer.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_utils.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_border.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_decoder.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_buf_vg_lite.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_grad.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_label.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_img.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_math.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_arc.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_pending.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_vector.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite_line.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_path.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_draw_vg_lite.c".}
{.compile: "../submodules/lvgl/src/draw/vg_lite/lv_vg_lite_stroke.c".}
